import {
  spfOne,
  spfTwo,
  spfThree,
  spfFour,
  bestSellerOne,
  bestSellerTwo,
  bestSellerThree,
  bestSellerFour,
  newArrOne,
  newArrTwo,
  newArrThree,
  newArrFour,
} from "../assets/images/index";

// =================== NavBarList Start here ====================
export const navBarList = [
  {
    _id: 1001,
    title: "Home",
    link: "/",
  },
  {
    _id: 1002,
    title: "Shop",
    link: "/shop",
  },
  {
    _id: 1003,
    title: "About",
    link: "/about",
  },
  {
    _id: 1004,
    title: "Contact",
    link: "contact",
  },
  {
    _id: 1005,
    title: "Manga",
    link: "/manga",
  },
];
// =================== NavBarList End here ======================
// =================== Special Offer data Start here ============
export const SplOfferData = [
  {
    _id: "201",
    img: spfOne,
    productName: "Rimuru(Tensura) Pure Cotton",
    price: "8000",
    color: "offWhite",
    badge: true,
    des: "Coming Soon",
  },
  {
    _id: "202",
    img: spfTwo,
    productName: "Nobara(JJK) Pure Cotton",
    price: "7000",
    color: "Cream",
    badge: false,
    des: "Coming Soon",
  },
  {
    _id: "203",
    img: spfThree,
    productName: "Shizu(Tensura) Pure Cotton",
    price: "8000",
    color: "Black",
    badge: false,
    des: "Coming Soon",
  },
  {
    _id: "204",
    img: spfFour,
    productName: "Anime Girl Pure Cotton",
    price: "8000",
    color: "Black",
    badge: false,
    des: "Coming Soon",
  },
];
// =================== Special Offer data End here ==============

// =================== PaginationItems Start here ===============

export const newArrivals = [
  {
    _id: 991,
    img: spfOne,
    productName: "Rimuru(Tensura) Pure Cotton",
    price: "8000",
    color: "offWhite",
    badge: true,
    des: "Coming Soon",
  },
  {
    _id: 992,
    img: spfTwo,
    productName: "Nobara(JJK) Pure Cotton",
    price: "7000",
    color: "Cream",
    badge: true,
    des: "Coming Soon",
  },
  {
    _id: 993,
    img: spfThree,
    productName: "Shizu(Tensura) Pure Cotton",
    price: "8000",
    color: "Black",
    badge: true,
    des: "Coming Soon",
  },
  {
    _id: 993.1,
    img: spfThree,
    productName: "Shizu(Tensura) Pure Cotton",
    price: "8000",
    color: "Black",
    badge: true,
    des: "Coming Soon",
  },
  {
    _id: 994,
    img: spfFour,
    productName: "Anime Girl Pure Cotton",
    price: "8000",
    color: "Black",
    badge: true,
    des: "Coming Soon",
  },
  {
    _id: 994.1,
    img: spfFour,
    productName: "Anime Girl Pure Cotton",
    price: "8000",
    color: "Black",
    badge: true,
    des: "Coming Soon",
  },
  {
    _id: 995,
    img: bestSellerOne,
    productName: "Rimuru(Tensura) Pure Cotton",
    price: "8000",
    color: "offWhite",
    badge: true,
    des: "Coming Soon",
  }
]
export const bestOffers = [
  {
    _id: 9091,
    img: spfOne,
    productName: "Rimuru(Tensura) Pure Cotton",
    price: "8000",
    color: "offWhite",
    badge: true,
    des: "Coming Soon",
  },
  {
    _id: 9092,
    img: spfTwo,
    productName: "Nobara(JJK) Pure Cotton",
    price: "7000",
    color: "Cream",
    badge: true,
    des: "Coming Soon",
  },
  {
    _id: 9093,
    img: spfThree,
    productName: "Shizu(Tensura) Pure Cotton",
    price: "8000",
    color: "Black",
    badge: true,
    des: "Coming Soon",
  },
  {
    _id: 9093.1,
    img: spfThree,
    productName: "Shizu(Tensura) Pure Cotton",
    price: "8000",
    color: "Black",
    badge: true,
    des: "Coming Soon",
  },
  {
    _id: 9094,
    img: spfFour,
    productName: "Anime Girl Pure Cotton",
    price: "8000",
    color: "Black",
    badge: true,
    des: "Coming Soon",
  },
  {
    _id: 9094.1,
    img: spfFour,
    productName: "Anime Girl Pure Cotton",
    price: "8000",
    color: "Black",
    badge: true,
    des: "Coming Soon",
  },
  {
    _id: 9095,
    img: bestSellerOne,
    productName: "Rimuru(Tensura) Pure Cotton",
    price: "8000",
    color: "offWhite",
    badge: true,
    des: "Coming Soon",
  },
  {
    _id: 9096,
    img: bestSellerOne,
    productName: "Rimuru(Tensura) Pure Cotton",
    price: "8000",
    color: "offWhite",
    badge: true,
    des: "Coming Soon",
  },
  {
    _id: 9097,
    img: bestSellerOne,
    productName: "Rimuru(Tensura) Pure Cotton",
    price: "8000",
    color: "offWhite",
    badge: true,
    des: "Coming Soon",
  },
  {
    _id: 9098,
    img: bestSellerOne,
    productName: "Rimuru(Tensura) Pure Cotton",
    price: "8000",
    color: "offWhite",
    badge: true,
    des: "Coming Soon",
  },
]
export const specialOffers = [
  {
    _id: 90091,
    img: spfOne,
    productName: "Rimuru(Tensura) Pure Cotton",
    price: "8000",
    color: "offWhite",
    badge: true,
    des: "Coming Soon",
  },
  {
    _id: 90092,
    img: spfTwo,
    productName: "Nobara(JJK) Pure Cotton",
    price: "7000",
    color: "Cream",
    badge: true,
    des: "Coming Soon",
  },
  {
    _id: 90093,
    img: spfThree,
    productName: "Shizu(Tensura) Pure Cotton",
    price: "8000",
    color: "Black",
    badge: true,
    des: "Coming Soon",
  },
  {
    _id: 90094,
    img: spfFour,
    productName: "Anime Girl Pure Cotton",
    price: "8000",
    color: "Black",
    badge: true,
    des: "Coming Soon",
  }
]


export const paginationItems = [
  {
    _id: 1001,
    img: spfOne,
    productName: "Rimuru(Tensura) Pure Cotton",
    price: "8000",
    color: "offWhite",
    badge: true,
    des: "Coming Soon",
  },
  {
    _id: 1002,
    img: spfTwo,
    productName: "Nobara(JJK) Pure Cotton",
    price: "7000",
    color: "Cream",
    badge: false,
    des: "Coming Soon",
  },
  {
    _id: 1003,
    img: spfThree,
    productName: "Shizu(Tensura) Pure Cotton",
    price: "8000",
    color: "Black",
    badge: false,
    des: "Coming Soon",
  },
  {
    _id: 1004,
    img: spfFour,
    productName: "Anime Girl Pure Cotton",
    price: "8000",
    color: "Black",
    badge: false,
    des: "Coming Soon",
  },
  {
    _id: 1005,
    img: bestSellerOne,
    productName: "Rimuru(Tensura) Pure Cotton",
    price: "8000",
    color: "offWhite",
    badge: true,
    des: "Coming Soon",
  },
  {
    _id: 1006,
    img: bestSellerTwo,
    productName: "Nobara(JJK) Pure Cotton",
    price: "7000",
    color: "Cream",
    badge: false,
    des: "Coming Soon",
  },
  {
    _id: 1007,
    img: bestSellerThree,
    productName: "Shizu(Tensura) Pure Cotton",
    price: "8000",
    color: "Black",
    badge: false,
    des: "Coming Soon",
  },
  {
    _id: 1008,
    img: bestSellerFour,
    productName: "Anime Girl Pure Cotton",
    price: "8000",
    color: "Black",
    badge: false,
    des: "Coming Soon",
  },
  {
    _id: 1009,
    img: newArrOne,
    productName: "Rimuru(Tensura) Pure Cotton",
    price: "8000",
    color: "offWhite",
    badge: true,
    des: "Coming Soon",
  },
  {
    _id: 1010,
    img: newArrTwo,
    productName: "Nobara(JJK) Pure Cotton",
    price: "7000",
    color: "Cream",
    badge: false,
    des: "Coming Soon",
  },
  {
    _id: 1011,
    img: newArrThree,
    productName: "Shizu(Tensura) Pure Cotton",
    price: "8000",
    color: "Black",
    badge: false,
    des: "Coming Soon",
  },
  {
    _id: 1012,
    img: newArrFour,
    productName: "Anime Girl Pure Cotton",
    price: "8000",
    color: "Black",
    badge: false,
    des: "Coming Soon",
  },
  {
    _id: 10013,
    img: spfOne,
    productName: "Rimuru(Tensura) Pure Cotton",
    price: "8000",
    color: "offWhite",
    badge: true,
    des: "Coming Soon",
  },
  {
    _id: 1014,
    img: spfTwo,
    productName: "Nobara(JJK) Pure Cotton",
    price: "7000",
    color: "Cream",
    badge: false,
    des: "Coming Soon",
  },
  {
    _id: 1015,
    img: spfThree,
    productName: "Shizu(Tensura) Pure Cotton",
    price: "8000",
    color: "Black",
    badge: false,
    des: "Coming Soon",
  },
  {
    _id: 1016,
    img: spfFour,
    productName: "Anime Girl Pure Cotton",
    price: "8000",
    color: "Black",
    badge: false,
    des: "Coming Soon",
  },
  {
    _id: 1017,
    img: bestSellerOne,
    productName: "Rimuru(Tensura) Pure Cotton",
    price: "8000",
    color: "offWhite",
    badge: true,
    des: "Coming Soon",
  },
  {
    _id: 1018,
    img: bestSellerTwo,
    productName: "Nobara(JJK) Pure Cotton",
    price: "7000",
    color: "Cream",
    badge: false,
    des: "Coming Soon",
  },
  {
    _id: 1019,
    img: bestSellerThree,
    productName: "Shizu(Tensura) Pure Cotton",
    price: "8000",
    color: "Black",
    badge: false,
    des: "Coming Soon",
  },
  {
    _id: 1020,
    img: bestSellerFour,
    productName: "Anime Girl Pure Cotton",
    price: "8000",
    color: "Black",
    badge: false,
    des: "Coming Soon",
  },
  {
    _id: 1021,
    img: newArrOne,
    productName: "Rimuru(Tensura) Pure Cotton",
    price: "8000",
    color: "offWhite",
    badge: true,
    des: "Coming Soon",
  },
  {
    _id: 1022,
    img: newArrTwo,
    productName: "Nobara(JJK) Pure Cotton",
    price: "7000",
    color: "Cream",
    badge: false,
    des: "Coming Soon",
  },
  {
    _id: 1023,
    img: newArrThree,
    productName: "Shizu(Tensura) Pure Cotton",
    price: "8000",
    color: "Black",
    badge: false,
    des: "Coming Soon",
  },
  {
    _id: 1024,
    img: newArrFour,
    productName: "Anime Girl Pure Cotton",
    price: "8000",
    color: "Black",
    badge: false,
    des: "Coming Soon",
  },
  {
    _id: 1025,
    img: spfOne,
    productName: "Rimuru(Tensura) Pure Cotton",
    price: "8000",
    color: "offWhite",
    badge: true,
    des: "Coming Soon",
  },
  {
    _id: 1026,
    img: spfTwo,
    productName: "Nobara(JJK) Pure Cotton",
    price: "7000",
    color: "Cream",
    badge: false,
    des: "Coming Soon",
  },
  {
    _id: 1027,
    img: spfThree,
    productName: "Shizu(Tensura) Pure Cotton",
    price: "8000",
    color: "Black",
    badge: false,
    des: "Coming Soon",
  },
  {
    _id: 1028,
    img: spfFour,
    productName: "Anime Girl Pure Cotton",
    price: "8000",
    color: "Black",
    badge: false,
    des: "Coming Soon",
  },
  {
    _id: 1029,
    img: bestSellerOne,
    productName: "Rimuru(Tensura) Pure Cotton",
    price: "8000",
    color: "offWhite",
    badge: true,
    des: "Coming Soon",
  },
  {
    _id: 1030,
    img: bestSellerTwo,
    productName: "Nobara(JJK) Pure Cotton",
    price: "7000",
    color: "Cream",
    badge: false,
    des: "Coming Soon",
  },
  {
    _id: 1031,
    img: bestSellerThree,
    productName: "Shizu(Tensura) Pure Cotton",
    price: "8000",
    color: "Black",
    badge: false,
    des: "Coming Soon",
  },
  {
    _id: 1032,
    img: bestSellerFour,
    productName: "Anime Girl Pure Cotton",
    price: "8000",
    color: "Black",
    badge: false,
    des: "Coming Soon",
  },
  {
    _id: 1033,
    img: newArrOne,
    productName: "Rimuru(Tensura) Pure Cotton",
    price: "8000",
    color: "offWhite",
    badge: true,
    des: "Coming Soon",
  },
  {
    _id: 1034,
    img: newArrTwo,
    productName: "Nobara(JJK) Pure Cotton",
    price: "7000",
    color: "Cream",
    badge: false,
    des: "Coming Soon",
  },
  {
    _id: 1035,
    img: newArrThree,
    productName: "Shizu(Tensura) Pure Cotton",
    price: "8000",
    color: "Black",
    badge: false,
    des: "Coming Soon",
  },
  {
    _id: 1036,
    img: newArrFour,
    productName: "Anime Girl Pure Cotton",
    price: "8000",
    color: "Black",
    badge: false,
    des: "Coming Soon",
  },
  {
    _id: 1037,
    img: spfOne,
    productName: "Nobara(JJK) Pure Cotton",
    price: "7000",
    color: "Cream",
    badge: false,
    des: "Coming Soon",
  },
  {
    _id: 1038,
    img: spfTwo,
    productName: "Shizu(Tensura) Pure Cotton",
    price: "8000",
    color: "Black",
    badge: false,
    des: "Coming Soon",
  },
  {
    _id: 1039,
    img: spfThree,
    productName: "Anime Girl Pure Cotton",
    price: "8000",
    color: "Black",
    badge: false,
    des: "Coming Soon",
  },
  {
    _id: 1040,
    img: bestSellerFour,
    productName: "Rimuru(Tensura) Pure Cotton",
    price: "8000",
    color: "offWhite",
    badge: true,
    des: "Coming Soon",
  },
  {
    _id: 1041,
    img: bestSellerTwo,
    productName: "Nobara(JJK) Pure Cotton",
    price: "7000",
    color: "Cream",
    badge: false,
    des: "Coming Soon",
  },
  {
    _id: 1042,
    img: bestSellerThree,
    productName: "Shizu(Tensura) Pure Cotton",
    price: "8000",
    color: "Black",
    badge: false,
    des: "Coming Soon",
  },
  {
    _id: 1043,
    img: bestSellerFour,
    productName: "Anime Girl Pure Cotton",
    price: "8000",
    color: "Black",
    badge: false,
    des: "Coming Soon",
  },
  {
    _id: 1044,
    img: newArrOne,
    productName: "Rimuru(Tensura) Pure Cotton",
    price: "8000",
    color: "offWhite",
    badge: true,
    des: "Coming Soon",
  },
  {
    _id: 1045,
    img: newArrTwo,
    productName: "Nobara(JJK) Pure Cotton",
    price: "7000",
    color: "Cream",
    badge: false,
    des: "Coming Soon",
  },
  {
    _id: 1046,
    img: newArrThree,
    productName: "Shizu(Tensura) Pure Cotton",
    price: "8000",
    color: "Black",
    badge: false,
    des: "Coming Soon",
  },
];
// =================== PaginationItems End here =================
